import sys
content = open('std/png.alu').read()
content = content.replace('printf("File[0]: %d, File[41]: %d\\n", int(file_data[0]) & 255, int(file_data[41]) & 255); ', '')
content = content.replace('printf("File size: %d\\n", file_len); ', '')
content = content.replace('printf("IDAT len: %d, width: %d, height: %d, bpp: %d\\n", idat_len, width, height, bpp); ', '')
content = content.replace('printf("IDAT len: %d, IDAT[0]: %d, IDAT[1]: %d\\n", idat_len, int(idat_buf[0]) & 255, int(idat_buf[1]) & 255); ', '')
content = content.replace('printf("CMF: %d\\n", cmf);', '')
content = content.replace('printf("FLG: %d\\n", flg);', '')
content = content.replace('printf("BTYPE: %d, BFINAL: %d\\n", btype, bfinal);', '')
content = content.replace('printf("byte_pos: %d, bit_pos: %d, count: %d, bit_buf: %d\\n", bs.byte_pos, bs.bit_count, count, bs.bit_buf); ', '')
open('std/png.alu', 'w').write(content)
