name: Build iOS XCFramework

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Build ALU Compiler (C++)
        run: clang++ cpp_frontend/*.cpp -o cpp_frontend/alu_cxx -O3 -lcrypto -lssl
        
      - name: Build iOS SDK
        run: |
          ./cpp_frontend/alu_cxx build image_processor.alu --create-xcframework
          mv image_processor.xcframework ios-sdk/AluSDK.xcframework
      - name: Upload XCFramework Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AluSDK-iOS
          path: ios-sdk/AluSDK.xcframework/
